name: "Build / make"
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  make-check:
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        container: ['ubuntu:latest', 'fedora:latest']
    permissions:
      security-events: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      id: dependencies
      uses: ./.github/actions/install-dependencies

    - name: Configure sssd
      uses: ./.github/actions/configure

    - name: make
      shell: bash
      working-directory: x86_64
      run: |
        source ../contrib/fedora/bashrc_sssd
        make CFLAGS+="$SSS_WARNINGS -Werror"

    - name: make check
      shell: bash
      working-directory: x86_64
      run: |
        source ../contrib/fedora/bashrc_sssd
        make CFLAGS+="$SSS_WARNINGS -Werror" check

    - name: make distcheck
      shell: bash
      working-directory: x86_64
      run: |
        source ../contrib/fedora/bashrc_sssd
        AUX_DISTCHECK_CONFIGURE_FLAGS+=--with-smb-idmap-interface-version=5 make distcheck

    - name: Get distro name
      run: |
        echo "OS=$(grep '^ID' /etc/os-release)" >> $GITHUB_ENV

    - uses: actions/upload-artifact@v3
      with:
        name: configure-artifacts ${{ env.OS }}
        path: |
          x86_64/config.log
          x86_64/config.h
        if-no-files-found: error
