name: "ci"
on:
  pull_request:
jobs:
  system:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      shell: bash
      run: |
        set -ex
        sudo apt-get update
        sudo apt-get install -y podman docker-compose

    - name: Start podman socket
      shell: bash
      run: |
        sudo systemctl enable podman.socket
        sudo systemctl restart podman.socket

    - name: Checkout
      uses: actions/checkout@v7

    - name: Setup upterm session
      uses: owenthereal/action-upterm@v1

    - name: Bring up containers
      shell: bash
      env:
        DOCKER_HOST: unix:///run/podman/podman.sock
      run: |
          sudo docker-compose up --no-recreate --detach
    
    - name: Run command in container
      shell: bash
      env:
        DOCKER_HOST: unix:///run/podman/podman.sock
      run: |
          sudo podman ps -a
