name: Coverity scan
on:
  # run once daily at 12:30 UTC due to
  # https://scan.coverity.com/faq#frequency
  schedule:
    - cron: "* * * * *"
    #- cron:  '30 12 * * *'

jobs:
  coverity:
    runs-on: ubuntu-latest
    # FIXME: fedora:latest fails due to
    # https://bugzilla.redhat.com/show_bug.cgi?id=2048909
    container: fedora:34
    env:
      BUILD_NAME: "covscan"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate spec file
        run: |
          cp contrib/sssd.spec.in ./sssd.spec

          sed -iE "s/@PACKAGE_NAME@/sssd/g" ./sssd.spec
          sed -iE "s/@PACKAGE_VERSION@/covscan/g" ./sssd.spec
          sed -iE "s/@PRERELEASE_VERSION@/$GITHUB_RUN_NUMBER/g" ./sssd.spec

      - name: Install dependencies
        run: |
          sudo dnf -y update
          sudo dnf -y install dnf-plugins-core wget
          sudo dnf -y builddep --spec sssd.spec

      - name: Configure
        ## Remove make
        run: |
          source ./contrib/fedora/bashrc_sssd && reconfig
          pwd
          ls -l
          ls -l ../

      - name: Execute and submit coverity scan
        uses: vapier/coverity-scan-action@v1
        with:
          ## FIXME: Email, and check for token in sssd repo
          email: "jstephen@redhat.com"
          token: ${{ secrets.COVERITY_SCAN_TOKEN }}
