name: Coverity scan
on:
  # run once daily at 12:30 UTC due to
  # https://scan.coverity.com/faq#frequency
  schedule:
    - cron: "* * * * *"
    #- cron:  '30 12 * * *'

jobs:
  coverity:
    runs-on: ubuntu-latest
    # FIXME: fedora:latest fails due to
    # https://bugzilla.redhat.com/show_bug.cgi?id=2048909
    # container: fedora:34
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        id: dependencies
        uses: ./.github/actions/install-dependencies

      - name: Configure
        run: source ./contrib/fedora/bashrc_sssd && reconfig

      - name: Execute and submit coverity scan
        uses: vapier/coverity-scan-action@v1.2.0
        with:
          ## FIXME: Email, and check for token in sssd repo
          email: "jstephen@redhat.com"
          token: ${{ secrets.COVERITY_SCAN_TOKEN }}
          working-directory: x86_64
